### ISSUE TITLE
Mailchimp form integration

### ISSUE THREAD

**Issue by bmarshall511** [bmarshall511/wordpress-zero-spam#121]
Feature request via email:

Thanks for the amazing Wordpress plugin (Zero Span). I've been using it with great results on a bunch of sites and the multi-site support is fantastic. One thing I wish it had is Mailchimp form integration. Was going to try and code this, but thought I should perhaps reach out to you first.

After looking at how Zero Spam it is added to gravity forms I think adding to Mailchimp should be straightforward as well. Here are the relevant Chimp hooks:

add_filter('mc4wp_form_before_fields', )
add_filter('mc4wp_valid_form_request',)

Hope you decide it's worth implementing. Let me know if there is anything I can do to help.

Thanks again,
Vassili Z.

**Comment by vzeazy** [comment]
Hey Ben,

Thanks for adding this to the feature request. Since I emailed this to you, you've actually added the zero spam hook. However, the mailchimp-for-wordpress plugin only has a hook that will allow class addition to the containing div and not the form element itself (https://mc4wp.com/kb/add-css-class-to-form-element/).

What I setup initially was:

function mywebsite_validate_mc4wp_form( $valid ) {
	// zero spam validation
	if ( zerospam_is_valid() ) {
	  return true;
	} else {
	  // Invalid form submission.
	  return 'error';
	}
}
add_filter( 'mc4wp_valid_form_request', 'mywebsite_validate_mc4wp_form' );

Then some javascript to add the class:
$('.mc4wp-form').children('form').addClass('zerospam');

This seemed to work on initially testing, but after the latest update this hack broke. Not sure, but likely zero-spam javascript is running prior to this.

Perhaps a good approach would be to allow zerospam to also look at all forms with the the containing field having that class as well.

.zerospam",b+=",.zerospam form",b+=",

Not sure if this could cause any overlap though.

**Comment by bmarshall511** [comment]
@vzeazy It's been a long time coming, but Zero Spam now supports Mailchimp for WordPress forms! Sorry about the long wait.
