### ISSUE TITLE
Find a way to display the blocked spam message on Ninja Forms

### ISSUE THREAD

**Issue by bmarshall511** [bmarshall511/wordpress-zero-spam#194]
Currently, if spam is detected on a Ninja Form submission, the form submission stops, spam is logged, but no details are provided to the end user about what happened. Instead the submit button stays in the 'Processing' state.

**Comment by jaredatch** [comment]
This really applies to all 3rd integrations, maybe even some of the WP core ones.

Right now when spam is detected either a redirect is performed or `die()` is triggered.

The issue is almost every integration supported has the ability to be AJAXified.

WPForms, Gravity, NinjaForms etc all natively support form submission to happen via AJAX instead of native $_POST which reloads the page, if user wants (which is ideal in many different use cases).

When any of the existing integrations are configured as AJAX, it's not going to fail gracefully because of the `die` or `wp_redirect` (which won't redirect anyways with AJAX). So the end result is form will appear to just "hang" if spam was detected and entry was rejected.

The only real way to solve this issue, which would take some time and research, would be to further improve the integrations so that the error is triggered using available error handler/notice system each provider has available.

For WPForms this is pretty easy and could be done with minimal adjustments to the integration code. I'm not super familiar with internal APIs of other solutions but I assume it would be similar.

**Comment by bmarshall511** [comment]
Yeah, I've thought about that & will be digging deeper into each integration as I get time. Spend an hour or two this morning trying to figure out Ninja Forms & following what their docs say, but instead printing the error message. I'll keep digging though until I or someone else can figure it out.

**Comment by bmarshall511** [comment]
Closing this since with the latest release, NF is no longer supported. See the plugin FAQs for more information.
