### ISSUE TITLE
Page stuck on "You have been blocked from visiting this site by WordPress Zero Spam due to detected spam activity."from all over the world

### ISSUE THREAD

**Issue by wtt-martijn** [bmarshall511/wordpress-zero-spam#228]
We use WP5.5.1 And we have I page that is permanently blocked bij WP Zero Spam. Even with the plugin removed. How can I solve this. Did everything, whitelisted ip/cleaned all blocked/deinstalled/reinstalled. I am pulling all my hairs right now and have not much to spare. Can you help me please what is wrong.

Keep getting this message:
You have been blocked from visiting this site by WordPress Zero Spam due to detected spam activity.

When I change to a translated page than it is working only the main page has this issue.

**Comment by bmarshall511** [comment]
There's no way the plugin is blocking a page when it's removed. If this is what you're experiencing, it's due to something else. If you're getting blocked, its because your IP address was reported to be spam/malicious. v5 release allows more control over this to fine-tune to your specific needs. Update and see if it resolves your issue. If not, either whitelist you IP address or adjust the strictness of the settings.
