### ISSUE TITLE
PHP Warning: Cannot modify header information

### ISSUE THREAD

**Issue by viktorix** [bmarshall511/wordpress-zero-spam#229]
Noticed this PHP warning in PHP 7.4. Not sure about other versions.

`PHP Warning:  Cannot modify header information - headers already sent in /wp-content/plugins/zero-spam/classes/class-wpzerospam.php on line 938`

Both the WP and Zero Spam are running the latest versions.

**Comment by timreeves** [comment]
I'm seeing this too, with PHP 7.3

Funny thing is, the warning is not generated during normal use of backend or frontend WordPress. It happens when any wp-cron job is called. So I read a good tutorial here: https://wpshout.com/wp_schedule_event-examples/ and also installed the plugin wp-crontrol to be able to start jobs manually. Every time I do so - ANY wp-cron job - the error is generated (several times):

[15-Oct-2020 22:26:00] WARNING: [pool example.com] child 3338 said into stderr: "NOTICE: PHP message: PHP Warning: Cannot modify header information - headers already sent in /var/www/vhosts/example.com/httpdocs/wp-content/plugins/zero-spam/classes/class-wpzerospam.php on line 938"

Looking at that, it's in a function set_cookie, which is called at lines 338 and 578 of class-wpzerospam.php. The for me open question is, WHY is a set cookie function being called during a wp-cron run? I don't see that you have hooked into wp_schedule_event (no own wp-cron job), so what is causing some of your code to be called during any wp-cron run? I'm out of my depth here... But I can say that I took an unused website (which was in "coming soon" mode), deactivated ALL plugins except wp-zero-spam, and even selected the standard 2020 theme from WP - and it was still happening.

I'm scuppered, but would be most grateful if you could look at this, Ben.

Thanks (and for a great plugin)

Tim

**Comment by timreeves** [comment]
WHMCS Bridge is causing a similar problem, but due to attempted session start. Looking at the code there, he's protected the session_start() with following test:

if (session_status() == PHP_SESSION_NONE)

But it's missing the test if headers have already been sent, see https://www.php.net/manual/en/function.headers-sent.php. And there's also the question of a session having been started and closed again.

So the protection should be beefed up to:

if (session_status() == PHP_SESSION_NONE and !headers_sent())

That said, I still have no idea _why_ the plugins code is being run - but I do have an idea _what_ is being called: The wp_init() function calls get_access(), which in turn calls set_access_cookies() several times, which in turn calls set_cookie(). This would match to the several instances of the PHP warning per wp-cron job.

So it looks very much as if the wp-cron mechanism is calling the registered init functions of all plugins - possibly to make sure that anything that any particular job tries to do will not fail because of non-initialised plugins. But still - why should the init functions be called again - since wp.-cron runs after a page is served, they will all have been called already.

Hope someone can shed more light on this...

Cheers, Tim

**Comment by timreeves** [comment]
My suggestion for beefing up the WHMCS Bridge test before calling setcookie() does indeed prevent the Warning. But I still would really like to uderstand what's going on with wp-cron.
Cheers, Tim

**Comment by therealgilles** [comment]
I had encountered a similar situation with the WP Session Manager plugin. This thread may provide insight: [https://github.com/ericmann/wp-session-manager/issues/81](https://github.com/ericmann/wp-session-manager/issues/81)

**Comment by bmarshall511** [comment]
v5 was just released and included major performance enhancements and a more implied approach that should fix issues like these. Please let me know if you're still running into it after upgrading.
