### ISSUE TITLE
Reintegrate David Walsh's technique for stopping spam [FEATURE]

### ISSUE THREAD

**Issue by bmarshall511** [bmarshall511/wordpress-zero-spam#247]
See https://davidwalsh.name/wordpress-comment-spam

**Comment by bmarshall511** [comment]
v5.0.8 has integration with the core comments form. More planned for future releases.

**Comment by kamil-vojtek** [comment]
Hi, can I ask what was the reason for dropping this by default in version 5?

**Comment by SummerBrooks** [comment]
@bmarshall511  What is the proper configuration for this feature?

I had left that feature disabled, but now I'm receiving more than 1-2Mb additions to error_log, per day, full of this error:

**PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, class 'ZeroSpam\Modules\Comments\Comments' does not have a method 'enqueue_davidwalsh' in /wp-includes/class-wp-hook.php on line 287**

I have since downgraded back to v4.10.2

**Comment by bmarshall511** [comment]
@SummerBrooks This has been fixed in the latest release (v5.0.10)

**Comment by SummerBrooks** [comment]
I shall update a couple of my sites as soon as the update shows as available!

**Comment by bmarshall511** [comment]
Update: 5.0.12 will have David Walsh support for WPForms.

**Comment by bmarshall511** [comment]
@SummerBrooks Hopefully your issue has been resolved, if not let me know. Also if you could rate the plugin, I'd really appreciate it: https://wordpress.org/plugins/zero-spam/
