### ISSUE TITLE
[BUG] Many IP blocked by mistake

### ISSUE THREAD

**Issue by matteoraggi** [bmarshall511/wordpress-zero-spam#257]
**Describe the bug**
Today me and my firends we discovered that the website www.letturadeicristalli.it is blocked to us, because he recognyze us as spammer, here our ip:
176.201.17.193
177.37.173.137 (a new macbook pro with safari and all updated software)
190.167.47.59 (a chromebook with chrome all updated)

Here the erro that we read: https://ibb.co/tm8Y8TX
To me it looks strange that going to the log these IP are not being blocked instead: wp-admin/index.php?page=wordpress-zero-spam-dashboard&tab=log
The issues disappeared disabling and enablig the plugin. 
The issue appeared at the 10 am of today and disappeared only 7 hours later when I disabled and enabled the plugin.

**Comment by Oizaro** [comment]
Same here. I'm been flagged as spam/malicious on website: www.plaffo.com

**Comment by bmarshall511** [comment]
You'll need to check the spam blacklists to determine why your IP is getting blocked. Zero Spam doesn't block people indiscriminately, it uses 3rd-party API from known spammy IPs. If you're getting blocked, it's likely because your IP appears on one of those lists. Be sure to double-check the plugin settings as well. You can control how strict things are from there.
