### ISSUE TITLE
DOS the "Sync Disallowed Keys" really Sync?

### ISSUE THREAD

**Issue by konsti2020** [bmarshall511/wordpress-zero-spam#259]
At first this plugin dos a great job.
But I have a additional question:

Dos the "Sync Disallowed Keys" Function in the Zero Spam plugin really synchronize the word lists or does it simply overwrite the existing list with the new one?

It would be great if I could add my own blacklist keywords for mailing domains that spamming my forms.

An alternative could be a text box to add those individual keywords/mailing domains.
Also it would be great for disallowing trash mail domains.

Best regards

Konsti

**Comment by bmarshall511** [comment]
Yes it syncs, however, the latest version reads from a blacklist text file located in the plugin directory vs. getting it remotely (due to Git's terms of use). It overrides the values. Allowing you to add additional/edit it would be a great feature request. Please resubmit as a feature request when creating an issue using an appropriate title and what the actual request is using the Feature format.

Closing for now.
